# theme: jekyll-theme-basically-basic
remote_theme: jekyll/minima
title: Span of Reference
email: edgamat@outlook.com
description: A blog about software development ideas
author: 'Matthew Edgar'
show_excerpts: true
# paginate: 3

minima:
  social_links:
    twitter: edgamat
    github: edgamat

# Octopress
post_ext: md
page_ext: html
